package com.lugtech.bukkitautogen.yaml;

import java.io.InputStream;
import java.io.PrintStream;
import java.util.Scanner;

public class Yaml {
	
	private final YamlNode rootNode;
	
	public static boolean LOG = false;
	private static PrintStream LOGFILE = null;
	
	public Yaml() {
		log("CREATED NEW EMPTY YAML FILE\n");
		rootNode = new YamlNode(0);
	}
	public Yaml(final InputStream input) {
		log("PARSING YAML FILE");
		rootNode = new YamlNode(0, new Scanner(input));
		log("PARSING COMPLETE\n");
	}
	
	public YamlNode getRootNode() {
		return rootNode;
	}
	
	public void save(PrintStream output) {
		log("SAVING YAML FILE");
		PrintStream writer = new PrintStream(output);
		writer.println("# THIS FILE IS AUTOMATICALLY GENERATED. ANY CHANGES WILL BE OVERWRITTEN");
		rootNode.write(writer);
		writer.close();
		log("SAVING COMPLETE\n");
	}
	
	public static void logFile(PrintStream logFile) {
		Yaml.LOGFILE = logFile;
	}
	
	private static void log(String line) {
		if (!LOG)
			return;
		System.out.println(line);
		if (LOGFILE == null)
			return;
		LOGFILE.println(line);
	}
	public static void log(int depth, String line) {
		line = " " + line;
		for (int i = 0; i < depth; i++)
			line = "  " + line;
		line = depth + line;
		log(line);
	}
}
